config/routes.rb
Rails.application.routes.draw do
root "pages#home"
  get "about", to: "pages#about"

  resources :articles
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user

    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord

before_save { self.email = email.downcase }

has_many :articles

validates :username, presence: true,
                 uniqueness: { case_sensitive: false },
                  length: { minimum: 3, maximum: 25 }

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true,
                 uniqueness: { case_sensitive: false },
                 length: { maximum: 105 },
                 format: { with: VALID_EMAIL_REGEX }

has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:show, :edit, :update, :destroy]

    def show
    end
  
    def index
      @articles = Article.all
    end
  
    def new
      @article = Article.new
    end

    def edit
    end


    
  
    def create
      @article = Article.new(article_params)
      @article.user = User.first
      if @article.save
        flash[:notice] = "Article was created successfully."
        redirect_to @article
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
        if @article.update(article_params)
            flash[:notice] = "Article was updated successfully"
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end
    
  
    private
  
    def article_params
      params.require(:article).permit(:title, :description)
    end

    def set_article
        @article = Article.find(params[:id])   
    end
        

    
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Create a new article</h1>

<!-- <turbo-frame id="new_article"> -->
  <% if @article.errors.any? %>
    <div style="color: red; border: 1px solid red; padding: 10px; margin-bottom: 15px;">
      <h2>The following errors prevented the article from being saved:</h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @article,  local: true) do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </p>

    <p>
      <%= f.submit "Save Article" %>
    </p>
  <% end %>
<!-- </turbo-frame> -->

<%= link_to 'Canel Edit & Return to Articles Listing', articles_path %>

app/views/articles/index.html.erb
<h1>Articles Listing Page: </h1>

<table>
    <thead>
        <tr>
            <th>Username</th>
            <th>Title</th>
            <th>Description</th>
            <th colspan="3">Actions</th>
        </tr>
    </thead>

    <tbody>
        <% @articles.each do |article| %>
        <tr>
            <td>
                <h4>By: <%= article.user.username if article.user %></h4>
            </td>
            <td>
                <%= article.title %>
            </td>
            <td>
                <%= article.description %>
            </td>
            <td>
                <%= link_to 'Show', article_path(article) %>
            </td>
            <td>
                <%= link_to 'Delete', article_path(article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
            </td>

            <td><%= link_to 'Edit', edit_article_path(article) %></td>


        </tr>
        <% end %>
    </tbody>

</table>
<p><%= link_to 'New Article', new_article_path(@article) %></p>
<br>
<p> <%= link_to 'Home Page:', root_path  %> </p>
<br>
<%=  link_to 'About Path:', about_path %>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<!-- <turbo-frame id="new_article"> -->
  <% if @article.errors.any? %>
    <div style="color: red; border: 1px solid red; padding: 10px; margin-bottom: 15px;">
      <h2>The following errors prevented the article from being saved:</h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with scope: :article, url: articles_path, local: true do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </p>

    <p>
      <%= f.submit "Save Article" %>
    </p>
  <% end %>
<!-- </turbo-frame> -->

<%= link_to 'Return to Articles Listing', articles_path %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>


<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>
<p><strong>Username: </strong> <%= @article.user.username if @article.user %> </p>


<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Delete', article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<%= link_to 'Return to Articles Listing', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Alpha Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
    <%= msg %>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Alpha Blog</h1>
<p>This is a blog for learning Rails.</p>

<%= link_to 'Home Page', root_path  %>
<br>
<%= link_to 'Go to Articles Listing', articles_path %>

app/views/pages/home.html.erb
<h1>Welcome to Alpha Blog!</h1>
<p>This is the home page.</p>

<%= link_to 'Go to Articles Listing', articles_path %>
<br>
<%= link_to 'About Path', about_path %>